package model;

import utils.Utils;

import java.time.LocalDate;

public class Card {
    private final String cardNumber;
    private String pin_code;
    private LocalDate expirationDate;
    private String CVV;


    public Card(String firstDigit, String bankDigits){
        this.cardNumber = generateCardNumber(firstDigit, bankDigits);
        this.pin_code = generatePinCode();
        this.expirationDate = LocalDate.now().plusYears(10L);
        this.CVV = generateCVV();
    }

    /// first digit identifies the Visa or Mastercard
    /// bankDigits - 5 digits that is randomly generated by bank
    private String generateCardNumber(String firstDigit, String bankDigits){
        String cardNumber = "";
        /// 5 digits that are generated by the bank
        String generatedDigits1 = Utils.generateNumbers(5);
        /// another 5 digits that are generated by the bank
        String generatedDigits2 = Utils.generateNumbers(5);

        cardNumber = firstDigit
                + bankDigits
                + generatedDigits1
                + generatedDigits2;
        return cardNumber;
    }

    private String generatePinCode(){
        String pin_code = Utils.generateNumbers(4);
        return pin_code;
    }

    private String generateCVV(){
        String CVV = Utils.generateNumbers(3);
        return CVV;
    }


    public String getCardNumber(){
        return cardNumber;
    }

    public String getPinCode(){
        return pin_code;
    }

    public LocalDate getExpirationDate(){
        return expirationDate;
    }

    public String getCVV(){
        return CVV;
    }

    @Override
    public String toString() {
        return "Card{" +
                "cardNumber='" + cardNumber + '\'' +
                ", pin_code=" + pin_code +
                ", expirationDate=" + expirationDate +
                ", CVV=" + CVV +
                '}';
    }
}




