package model;

import utils.GenerateInfo;

import java.time.LocalDate;

public class Card {
    private String cardNumber;
    private String pin_code;
    private LocalDate expirationDate;
    private String CVV;
    private Client client;


    public Card(Client client, String firstDigit, String bankDigits){
        this.client = client;
        generateCardNumber(firstDigit, bankDigits);
        generatePinCode();
        expirationDate = LocalDate.now().plusYears(10L);
        generateCVV();
    }


    private String generatePinCode(){
        pin_code = GenerateInfo.generateNumbers(4);
        return this.pin_code;
    }

    /// first digit identifies the Visa or Mastercard
    /// bankDigits - 5 digits that is randomly generated by bank

    private String generateCardNumber(String firstDigit, String bankDigits){
        String generatedDigits1 = GenerateInfo.generateNumbers(5);
        /// another 5 digits that are generated by bank
        String generatedDigits2 = GenerateInfo.generateNumbers(5);

        cardNumber = firstDigit
                + bankDigits
                + generatedDigits1
                + generatedDigits2;
        return this.cardNumber;
    }

    private String generateCVV(){
        CVV = GenerateInfo.generateNumbers(3);
        return CVV;
    }


    public String getCardNumber(){
        return cardNumber;
    }

    public String getPinCode(){
        return pin_code;
    }

    public LocalDate getExpirationDate(){
        return expirationDate;
    }

    public String getCVV(){
        return CVV;
    }

    public Client getHolder(){
        return client;
    }


    @Override
    public String toString() {
        return "Card{" +
                "cardNumber='" + cardNumber + '\'' +
                ", pin_code=" + pin_code +
                ", expirationDate=" + expirationDate +
                ", CVV=" + CVV +
                ", holder=" + client +
                '}';
    }
}




